### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by lgatto** [BulliedIntoBadScience/BulliedIntoBadScience.org#1]
- [x] make sure to credit all images
  - trinity.png - Credit: David Liff, CC-BY-SA 3.0
  - petition -  Petition by Nick Youngson (http://nyphotographic.com/), licensed under a CC BY SA 3.0 license.
  - Corina and Laurent - Torsten Krude, CC-BY
- [X] Credit translators
   - [X] German translation by Dieter Lukas
- [ ] The anectodes should be printed as quotes, possibly with a next/prev button - see issue #2 
- [x] Adapt footer.
- [x] Fix css on github pages 
- [x] Fix javascript on github pages
